apiVersion: apps/v1
kind: Deployment
metadata:
  name: inanna-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inanna-ai
  template:
    metadata:
      labels:
        app: inanna-ai
    spec:
      containers:
        - name: inanna-ai
          image: spiral_os:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20

